# Generated by Django 4.2.1 on 2023-08-12 00:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_thumbnail_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
                verbose_name="color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name="size"),
        ),
    ]
