# Generated by Django 4.2.4 on 2023-10-02 19:18

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models

import apps.products.utils


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_color_remove_product_size_remove_product_color_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productadvertising",
            options={"verbose_name": "Product Advertising", "verbose_name_plural": "Product Advertisings"},
        ),
        migrations.AlterField(
            model_name="category",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="The group that the category belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="products.groupcategory",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Name of the category (e.g: 'Watches')",
                max_length=255,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                db_index=True,
                help_text="Name of the category (e.g: 'Watches')",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_fr",
            field=models.CharField(
                db_index=True,
                help_text="Name of the category (e.g: 'Watches')",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(help_text="Slug of the category (e.g: 'watches')", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                help_text="Thumbnail of the category",
                keep_meta=True,
                null=True,
                quality=90,
                scale=None,
                size=[200, 200],
                upload_to=apps.products.utils.thumbnail_path_category,
                verbose_name="thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="name",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                help_text="Color of the product",
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
                verbose_name="color",
            ),
        ),
        migrations.AlterField(
            model_name="groupcategory",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Name of the group category (e.g: 'Electronics')",
                max_length=255,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="groupcategory",
            name="name_en",
            field=models.CharField(
                db_index=True,
                help_text="Name of the group category (e.g: 'Electronics')",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="groupcategory",
            name="name_fr",
            field=models.CharField(
                db_index=True,
                help_text="Name of the group category (e.g: 'Electronics')",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="groupcategory",
            name="slug",
            field=models.SlugField(
                help_text="Slug of the group category (e.g: 'electronics')",
                max_length=255,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="groupcategory",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                help_text="Thumbnail of the group category",
                keep_meta=True,
                null=True,
                quality=90,
                scale=None,
                size=[200, 200],
                upload_to=apps.products.utils.thumbnail_path_category,
                verbose_name="thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category of the product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(
                blank=True, help_text="Color of the product", related_name="products", to="products.color"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the product", null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="Description of the product", null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_fr",
            field=models.TextField(
                blank=True, help_text="Description of the product", null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Name of the product (e.g: 'Apple Watch')",
                max_length=255,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                db_index=True,
                help_text="Name of the product (e.g: 'Apple Watch')",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_fr",
            field=models.CharField(
                db_index=True,
                help_text="Name of the product (e.g: 'Apple Watch')",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price of the product",
                max_digits=10,
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                help_text="The promotion of the product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.promotion",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="Slug of the product (e.g: 'apple-watch')",
                max_length=255,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Stock quantity of the product", verbose_name="stock quantity"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                help_text="Thumbnail of the product",
                keep_meta=True,
                null=True,
                quality=90,
                scale=None,
                size=[500, 500],
                upload_to=apps.products.utils.thumbnail_path_product,
                verbose_name="thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="productadvertising",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the advertising", null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="productadvertising",
            name="product",
            field=models.OneToOneField(
                help_text="Product of the advertising",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertising",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productadvertising",
            name="title",
            field=models.CharField(
                help_text="Title of the advertising", max_length=255, unique=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                help_text="Image of the product",
                keep_meta=True,
                null=True,
                quality=90,
                scale=None,
                size=[700, 700],
                upload_to=apps.products.utils.thumbnail_path_product,
                verbose_name="thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Product of the image",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount",
            field=models.IntegerField(
                default=0,
                help_text="Discount of the promotion",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="discount",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateTimeField(help_text="End date of the promotion", verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start_date",
            field=models.DateTimeField(help_text="Start date of the promotion", verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="title",
            field=models.CharField(
                help_text="Title of the promotion",
                max_length=255,
                unique=True,
                verbose_name="title of promotion",
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="color",
            table="colors",
        ),
        migrations.AlterModelTable(
            name="groupcategory",
            table="groupCategories",
        ),
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
        migrations.AlterModelTable(
            name="productadvertising",
            table="productAdvertisings",
        ),
        migrations.AlterModelTable(
            name="productimage",
            table="productImages",
        ),
        migrations.AlterModelTable(
            name="promotion",
            table="promotions",
        ),
    ]
