# Generated by Django 4.2.4 on 2023-10-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_productadvertising_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(
                blank=True,
                db_table="productColors",
                help_text="Color of the product",
                related_name="products",
                to="products.color",
            ),
        ),
    ]
