# Generated by Django 4.2.1 on 2023-08-08 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartProxy",
            fields=[],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cart.cart",),
        ),
        migrations.CreateModel(
            name="OrderItemProxy",
            fields=[],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Orders Items",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cart.orderitem",),
        ),
        migrations.CreateModel(
            name="PaymentProxy",
            fields=[],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments.payment",),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("public_id", models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="total price"),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                        verbose_name="order status",
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="order date"),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="delivery date"),
                ),
                (
                    "orders_items",
                    models.ManyToManyField(blank=True, related_name="orders", to="cart.orderitem"),
                ),
                (
                    "payement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="payments.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "order",
                "ordering": ["-order_date"],
            },
        ),
    ]
