# Generated by Django 4.2.4 on 2023-12-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Order Item", "verbose_name_plural": "Orders Items"},
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="public_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Unique identifier for this object. This is used to identify ",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="public_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Unique identifier for this object. This is used to identify ",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name="updated at"),
        ),
    ]
