# Generated by Django 4.2.1 on 2023-05-12 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='order status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('awaiting_payment', 'Awaiting payment'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='payment status')),
                ('order_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='order date')),
                ('payment_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='payment date')),
                ('delivery_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='delivery date')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': ' Carts',
                'db_table': 'cart',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price')),
                ('ordered', models.BooleanField(db_index=True, default=False, verbose_name='ordered')),
                ('order_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='order date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': '  Orders',
                'db_table': 'orders',
                'ordering': ['-order_date'],
            },
        ),
    ]
