# Generated by Django 4.2.4 on 2023-12-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Unique identifier for this object. This is used to identify ",
                max_length=64,
                unique=True,
            ),
        ),
    ]
