# Generated by Django 4.2.1 on 2023-05-12 21:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('verified', models.BooleanField(db_index=True, default=False, verbose_name='verified')),
                ('timestamp_requested', models.DateTimeField(auto_now_add=True, verbose_name='timestamp requested')),
                ('timestamp_verified', models.DateTimeField(null=True, verbose_name='timestamp verified')),
            ],
            options={
                'verbose_name': 'verification code',
                'verbose_name_plural': 'verification codes',
                'db_table': 'phoneNumberCheck',
            },
        ),
        migrations.CreateModel(
            name='GroupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
