# Generated by Django 4.2.1 on 2023-09-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authUser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codechecker",
            name="token",
            field=models.CharField(max_length=300),
        ),
    ]
