# Generated by Django 4.2.1 on 2023-05-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='street address')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City or neighborhood')),
                ('zipcode', models.CharField(blank=True, max_length=12, null=True, verbose_name='Zip / Postal code')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'address',
                'ordering': ['-user__date_joined'],
            },
        ),
    ]
